version: '3.8'

# Development override for docker-compose.yml
services:
  # MongoDB Database
  mongodb:
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  # Redis Cache
  redis:
    ports:
      - "6379:6379"

  # Backend API (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-admin123}@mongodb:27017/${MONGO_DB_NAME:-blog_platform}?authSource=admin
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET:-dev-jwt-secret-key}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-dev-refresh-jwt-secret-key}
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
      - ./backend/logs:/app/logs
      - ./backend/uploads:/app/uploads
    command: ["dumb-init", "npm", "run", "dev"]

  # Frontend React App (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    environment:
      VITE_API_URL: http://localhost:5000/api
      VITE_APP_NAME: Blog Platform (Dev)
      VITE_APP_DESCRIPTION: A modern blog platform built with MERN stack
      VITE_APP_VERSION: 1.0.0-dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    command: ["dumb-init", "npm", "run", "dev"]

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  redis_data:
    driver: local

networks:
  blog-network:
    driver: bridge